#include <algorithm>
#include <array>
#include <chrono>
#include <iostream>
#include <vector>
struct Edge{int i,j,s;};
int tiny(const std::vector<Edge>& es){int a[3][3]={{0}};int n=es.size();for(int i=0;i<n;i++)for(int j=0;j<n;j++)a[i][j]=(i==j)+es[i].s*(es[i].j==es[j].i);if(n==1)return a[0][0];if(n==2)return a[0][0]*a[1][1]-a[0][1]*a[1][0];return a[0][0]*(a[1][1]*a[2][2]-a[1][2]*a[2][1])-a[0][1]*(a[1][0]*a[2][2]-a[1][2]*a[2][0])+a[0][2]*(a[1][0]*a[2][1]-a[1][1]*a[2][0]);}
long independent(const std::vector<Edge>& es){std::vector<int>v;for(auto e:es){v.push_back(e.i);v.push_back(e.j);}std::sort(v.begin(),v.end());v.erase(std::unique(v.begin(),v.end()),v.end());int n=v.size();long a[6][6]={{0}},sgn=1,prev=1;for(int i=0;i<n;i++)a[i][i]=1;for(auto e:es){int i=std::find(v.begin(),v.end(),e.i)-v.begin(),j=std::find(v.begin(),v.end(),e.j)-v.begin();a[i][j]=e.s;}for(int k=0;k<n-1;k++){int p=k;while(p<n&&!a[p][k])p++;if(p==n)return 0;if(p!=k){for(int j=0;j<n;j++)std::swap(a[p][j],a[k][j]);sgn=-sgn;}long pivot=a[k][k];for(int i=k+1;i<n;i++)for(int j=k+1;j<n;j++){long t=a[i][j]*pivot-a[i][k]*a[k][j];if(t%prev){std::cerr<<"nonexact";exit(2);}a[i][j]=t/prev;}for(int i=k+1;i<n;i++)a[i][k]=0;prev=pivot;}return sgn*a[n-1][n-1];}
int main(int argc,char**argv){int n=argc>1?atoi(argv[1]):9,m=argc>2?atoi(argv[2]):n;auto start=std::chrono::steady_clock::now();std::vector<Edge>slots;for(int i=0;i<m;i++)for(int j=0;j<n;j++)if(i!=j)slots.push_back({i,j,1});std::cout<<"{\"dimension\":"<<n<<",\"free_rows\":"<<m<<",\"by_entries\":[";bool first=true;for(int r=1;r<=3;r++){long counts[3]={0};std::vector<int>ids(r);for(int i=0;i<r;i++)ids[i]=i;for(;;){for(int signs=0;signs<(1<<r);signs++){std::vector<Edge>es;for(int i=0;i<r;i++){auto e=slots[ids[i]];e.s=(signs>>i&1)?1:-1;es.push_back(e);}int d=tiny(es);long q=independent(es);if(d!=q||d<0||d>2){std::cerr<<"MISMATCH";return 3;}counts[d]++;}int p=r-1;while(p>=0&&ids[p]==(int)slots.size()-r+p)p--;if(p<0)break;ids[p]++;for(int j=p+1;j<r;j++)ids[j]=ids[j-1]+1;}if(!first)std::cout<<",";first=false;std::cout<<"{\"entries\":"<<r<<",\"det0\":"<<counts[0]<<",\"det1\":"<<counts[1]<<",\"det2\":"<<counts[2]<<"}";}double seconds=std::chrono::duration<double>(std::chrono::steady_clock::now()-start).count();std::cout<<"],\"seconds\":"<<seconds<<",\"independent_bareiss_agreement\":true}\n";}
